# Generated by Django 6.0.1 on 2026-02-01 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeviceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="例如：LED灯、智能风扇、继电器",
                        max_length=50,
                        unique=True,
                        verbose_name="设备类型名称",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="设备类型的详细说明",
                        verbose_name="类型描述",
                    ),
                ),
                (
                    "default_variables_schema",
                    models.JSONField(
                        default=dict,
                        help_text='\n        定义设备类型的变量、数据类型和范围\n        示例：\n        {\n            "power_state": {\n                "type": "bool",\n                "default": false,\n                "writable": true,\n                "description": "电源状态"\n            },\n            "brightness": {\n                "type": "int",\n                "range": [0, 100],\n                "default": 100,\n                "unit": "%",\n                "writable": true,\n                "description": "亮度"\n            },\n            "speed": {\n                "type": "int",\n                "range": [0, 3],\n                "default": 1,\n                "writable": true,\n                "description": "速度档位"\n            }\n        }\n        ',
                        verbose_name="变量定义模板",
                    ),
                ),
                (
                    "device_parameters",
                    models.JSONField(
                        default=dict,
                        help_text='\n        定义设备参数的类型和取值范围\n        示例：\n        {\n            "heartbeat_interval": {\n                "type": "int",\n                "range": [10, 600],\n                "default": 60,\n                "unit": "秒",\n                "description": "心跳间隔"\n            },\n            "control_pin": {\n                "type": "string",\n                "options": ["D1", "D2", "D3", "D4"],\n                "default": "D1",\n                "description": "控制引脚"\n            }\n        }\n        ',
                        verbose_name="设备参数配置模板",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="前端显示用的图标名称",
                        max_length=50,
                        verbose_name="图标名称",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "设备类型",
                "verbose_name_plural": "设备类型",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="设备唯一ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="设备名称")),
                ("description", models.TextField(blank=True, verbose_name="设备描述")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="设备位置"
                    ),
                ),
                (
                    "mqtt_topic_data",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="数据主题"
                    ),
                ),
                (
                    "mqtt_topic_control",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="控制主题"
                    ),
                ),
                (
                    "is_online",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否在线"
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后上报时间"
                    ),
                ),
                (
                    "hardware_version",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="硬件版本"
                    ),
                ),
                (
                    "firmware_version",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="固件版本"
                    ),
                ),
                (
                    "mac_address",
                    models.CharField(blank=True, max_length=17, verbose_name="MAC地址"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "device_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devices",
                        to="devices.devicetype",
                        verbose_name="设备类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "设备",
                "verbose_name_plural": "设备列表",
            },
        ),
        migrations.CreateModel(
            name="DeviceData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        help_text="设备上报的数据，如：{'power_state': true, 'brightness': 80}",
                        verbose_name="数据内容",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        help_text="数据记录的时间戳",
                        verbose_name="数据时间",
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="服务器接收到数据的时间",
                        verbose_name="接收时间",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_records",
                        to="devices.device",
                        verbose_name="设备",
                    ),
                ),
            ],
            options={
                "verbose_name": "设备数据",
                "verbose_name_plural": "设备数据记录",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "-timestamp"],
                        name="devices_dev_device__246e80_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="devices_dev_timesta_b1901d_idx"
                    ),
                ],
            },
        ),
    ]
