# Generated by Django 5.2.8 on 2026-02-07 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="firmware_version",
        ),
        migrations.RemoveField(
            model_name="device",
            name="hardware_version",
        ),
        migrations.RemoveField(
            model_name="device",
            name="mac_address",
        ),
    ]
