# Generated by manual creation on 2026-02-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_remove_hardware_fields"),
    ]

    operations = [
        # 删除旧字段
        migrations.RemoveField(
            model_name="devicetype",
            name="default_variables_schema",
        ),
        migrations.RemoveField(
            model_name="devicetype",
            name="device_parameters",
        ),
        # 添加新字段
        migrations.AddField(
            model_name="devicetype",
            name="state_fields",
            field=models.JSONField(
                default=list,
                help_text='设备状态字段名称列表。示例：["power_state", "brightness"]',
                verbose_name="状态字段列表",
            ),
        ),
        migrations.AddField(
            model_name="devicetype",
            name="config_parameters",
            field=models.JSONField(
                default=list,
                help_text='可配置的参数名称列表。示例：["heartbeat_interval"]',
                verbose_name="配置参数列表",
            ),
        ),
    ]
