# Generated by Django 6.0.1 on 2026-02-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0004_devicetype_device_type_id_and_commands"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="device",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "设备",
                "verbose_name_plural": "设备列表",
            },
        ),
        migrations.AlterField(
            model_name="device",
            name="mqtt_topic_data",
            field=models.CharField(blank=True, max_length=200, verbose_name="状态主题"),
        ),
        migrations.AlterField(
            model_name="devicetype",
            name="DeviceType_id",
            field=models.CharField(
                db_index=True,
                help_text="例如：LED-01、FAN-01",
                max_length=50,
                unique=True,
                verbose_name="设备类型唯一ID",
            ),
        ),
        migrations.AlterField(
            model_name="devicetype",
            name="commands",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='\n        该类型设备支持的命令列表。示例：\n        {\n            "turn_on": {\n                "mqtt_message": {"command": "power_on"},\n                "description": "打开设备",\n                "params": []\n            },\n            "turn_off": {\n                "mqtt_message": {"command": "power_off"},\n                "description": "关闭设备",\n                "params": []\n            },\n            "set_brightness": {\n                "mqtt_message": {"command": "set_brightness", "value": "{val}"},\n                "description": "设置亮度",\n                "params": ["val"]\n            }\n        }\n        ',
                verbose_name="可用命令列表",
            ),
        ),
        migrations.AlterField(
            model_name="devicetype",
            name="state_fields",
            field=models.JSONField(
                default=list,
                help_text='设备上报的状态字段名称列表。示例：["power_state", "brightness"]',
                verbose_name="状态字段列表",
            ),
        ),
    ]
