# Generated by Django 6.0.1 on 2026-02-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0005_alter_device_options_alter_device_mqtt_topic_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicedata",
            name="check_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="设备回传的 check_code，与发送命令时的校验码对应",
                max_length=20,
                null=True,
                verbose_name="校验码",
            ),
        ),
    ]
