# Generated by Django 6.0.1 on 2026-02-14 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0006_add_check_code_to_device_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="devicedata",
            name="check_code",
        ),
    ]
