# Generated by Django 5.2.8 on 2026-02-17 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0007_remove_check_code_from_device_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="devicetype",
            name="icon",
        ),
    ]
