# Generated by Django 6.0.3 on 2026-05-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_unify_status_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='plant_code',
            field=models.CharField(blank=True, db_index=True, help_text='所属工艺装置代号，例如 "EB" 表示乙苯装置。空表示通用设备', max_length=50, verbose_name='所属装置代号'),
        ),
        migrations.AddField(
            model_name='device',
            name='plant_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='工艺场景下的扩展字段。示例：{"tag": "P-101", "area": "FEED"}', verbose_name='工艺元数据'),
        ),
    ]
