# Generated by Django 6.0.1 on 2026-02-12 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SensorType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "SensorType_id",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="设备类型唯一ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="例如：DHT11温湿度传感器、BMP180气压传感器",
                        max_length=50,
                        unique=True,
                        verbose_name="传感器类型名称",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="传感器类型的详细说明",
                        verbose_name="类型描述",
                    ),
                ),
                (
                    "data_fields",
                    models.JSONField(
                        default=list,
                        help_text='传感器上报的数据字段名称列表。示例：["temperature",""humidity"]',
                        verbose_name="数据字段列表",
                    ),
                ),
                (
                    "config_parameters",
                    models.JSONField(
                        default=list,
                        help_text='可配置的参数名称列表。示例：["samplingInterval", "is_enabled"]',
                        verbose_name="配置参数列表",
                    ),
                ),
                (
                    "commands",
                    models.JSONField(
                        default=list,
                        help_text='\n        该类型传感器支持的命令列表。示例：        \n        {\n            "turn_on": {\n                "mqtt_message": {"command": "enable"},\n                "description": "启动传感器",\n                "params": [] \n            },\n            "turn_off": {\n                "mqtt_message": {"command": "disable"},\n                "description": "关闭传感器",\n                "params": []\n            },\n            "set_interval": {\n                "mqtt_message": {\n                    "command": "set_interval",\n                    "interval": "{val}"\n                },\n                "description": "设置传输间隔",\n                "params": ["val"]\n            }\n        }\n        ',
                        verbose_name="可用命令列表",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "传感器类型",
                "verbose_name_plural": "传感器类型",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="设备唯一ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="设备名称")),
                ("description", models.TextField(blank=True, verbose_name="设备描述")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="设备位置"
                    ),
                ),
                (
                    "mqtt_topic_data",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="数据主题"
                    ),
                ),
                (
                    "mqtt_topic_control",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="控制主题"
                    ),
                ),
                (
                    "is_online",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否在线"
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后上报时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "sensor_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sensors",
                        to="sensors.sensortype",
                        verbose_name="传感器类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "传感器",
                "verbose_name_plural": "传感器列表",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        help_text="传感器上报的原始数据，如：{'temperature': 25.5, 'humidity': 60.0}",
                        verbose_name="数据内容",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        help_text="数据采集的时间戳",
                        verbose_name="数据时间",
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="服务器接收到数据的时间",
                        verbose_name="接收时间",
                    ),
                ),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_records",
                        to="sensors.sensor",
                        verbose_name="传感器",
                    ),
                ),
            ],
            options={
                "verbose_name": "传感器数据",
                "verbose_name_plural": "传感器数据记录",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["sensor", "-timestamp"],
                        name="sensors_sen_sensor__561443_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="sensors_sen_timesta_a94ae6_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SensorStatusCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        help_text="传感器上报的状态数据，如：{'is_enabled': true, 'samplingInterval': 120}",
                        verbose_name="数据内容",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        help_text="数据采集的时间戳",
                        verbose_name="数据时间",
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        blank=True,
                        help_text="传感器状态事件的名称，例如：online、offline、interval_updated",
                        max_length=100,
                        verbose_name="事件名称",
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="服务器接收到数据的时间",
                        verbose_name="接收时间",
                    ),
                ),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_records",
                        to="sensors.sensor",
                        verbose_name="传感器",
                    ),
                ),
            ],
            options={
                "verbose_name": "传感器状态数据",
                "verbose_name_plural": "传感器状态数据记录",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["sensor", "-timestamp"],
                        name="sensors_sen_sensor__86a223_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="sensors_sen_timesta_bf99ae_idx"
                    ),
                ],
            },
        ),
    ]
