# Generated by Django 6.0.3 on 2026-03-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_rename_device_id_to_sensor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_id',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='传感器唯一ID'),
        ),
    ]
