# Generated by Django 6.0.3 on 2026-05-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_sensor_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='plant_code',
            field=models.CharField(blank=True, db_index=True, help_text='所属工艺装置代号，例如 "EB" 表示乙苯装置。空表示通用传感器', max_length=50, verbose_name='所属装置代号'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='plant_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='工艺场景下的扩展字段。示例：\n{\n  "tag": "TT-101",          // 仪表位号\n  "area": "R1",             // 区域\n  "data_key": "temperature",// data 字段中的取值键\n  "unit": "K",\n  "normal_value": 434,\n  "hi_threshold": 440,\n  "lo_threshold": 425,\n  "severity": "high"        // low / mid / high / critical\n}', verbose_name='工艺元数据'),
        ),
    ]
