# Generated by Django 6.0.3 on 2026-03-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='唯一标识，如 mqtt_broker、site_name', max_length=100, unique=True, verbose_name='配置键')),
                ('value', models.TextField(blank=True, help_text='字符串存储，复杂结构可使用 JSON 格式', verbose_name='配置值')),
                ('category', models.CharField(default='general', help_text='如 mqtt、general、ui 等，便于分组管理', max_length=50, verbose_name='分类')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '平台配置',
                'verbose_name_plural': '平台配置',
                'ordering': ['category', 'key'],
            },
        ),
    ]
