# Generated by Django 6.0.3 on 2026-03-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformconfig',
            name='value',
            field=models.JSONField(blank=True, default=None, help_text='JSON 格式，支持字符串、数字、列表、字典等，如 "127.0.0.1"、1883、["DHT11-001"]、{"host":"x","port":1883}', null=True, verbose_name='配置值'),
        ),
    ]
