# Generated by Django 6.0.3 on 2026-04-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_settings', '0002_alter_platformconfig_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='与 plugins/ 下的目录名一致', max_length=100, unique=True, verbose_name='插件名')),
                ('enabled', models.BooleanField(default=True, help_text='启用/禁用后需重启 Django 进程才会影响 URL 路由', verbose_name='是否启用')),
                ('version', models.CharField(blank=True, default='', max_length=50, verbose_name='版本')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='说明')),
                ('installed_at', models.DateTimeField(auto_now_add=True, verbose_name='登记时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '插件',
                'verbose_name_plural': '插件',
                'ordering': ['name'],
            },
        ),
    ]
