# Generated by Django 6.0.3 on 2026-05-15 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0012_remove_device_plant_fields'),
        ('sensors', '0006_remove_sensor_plant_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='EBPlantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', help_text='默认仅一条 default，预留未来多套配置', max_length=50, unique=True, verbose_name='配置名')),
                ('view_settings', models.JSONField(blank=True, default=dict, help_text='例如 {"grid_cols": 4, "refresh_ms": 1000, "show_threshold_line": true}', verbose_name='视图设置')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'EB 大屏配置',
                'verbose_name_plural': 'EB 大屏配置',
            },
        ),
        migrations.CreateModel(
            name='EBPlantDeviceBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, help_text='如 P-101', max_length=50, verbose_name='设备位号')),
                ('area', models.CharField(blank=True, max_length=50, verbose_name='区域')),
                ('sort_order', models.IntegerField(db_index=True, default=0, verbose_name='显示顺序')),
                ('is_visible', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eb_binding', to='devices.device', verbose_name='主模型设备')),
            ],
            options={
                'verbose_name': 'EB 设备绑定',
                'verbose_name_plural': 'EB 设备绑定',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EBPlantSensorBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, help_text='如 TT-101', max_length=50, verbose_name='仪表位号')),
                ('area', models.CharField(blank=True, help_text='如 R1 / R2 / FEED', max_length=50, verbose_name='区域')),
                ('data_key', models.CharField(blank=True, help_text='从 SensorData.data 取值的字段名，留空则自动取唯一字段', max_length=50, verbose_name='数据键名')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='单位')),
                ('normal_value', models.FloatField(blank=True, null=True, verbose_name='正常值')),
                ('hi_threshold', models.FloatField(blank=True, null=True, verbose_name='高阈值')),
                ('lo_threshold', models.FloatField(blank=True, null=True, verbose_name='低阈值')),
                ('severity', models.CharField(choices=[('low', 'low'), ('mid', 'mid'), ('high', 'high'), ('critical', 'critical')], default='mid', max_length=20, verbose_name='严重度')),
                ('sort_order', models.IntegerField(db_index=True, default=0, verbose_name='显示顺序')),
                ('is_visible', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sensor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eb_binding', to='sensors.sensor', verbose_name='主模型传感器')),
            ],
            options={
                'verbose_name': 'EB 传感器绑定',
                'verbose_name_plural': 'EB 传感器绑定',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
