# Generated by Django 6.0.3 on 2026-05-16 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_remove_device_plant_fields'),
        ('plugin_eb_plant', '0001_initial'),
        ('sensors', '0006_remove_sensor_plant_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebplantdevicebinding',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eb_device_binding', to='devices.device', verbose_name='主模型设备'),
        ),
        migrations.AlterField(
            model_name='ebplantsensorbinding',
            name='data_key',
            field=models.CharField(blank=True, help_text='从 SensorData.data 取值的字段名，留空表示自动取唯一字段（仅在传感器只有一个字段时有意义）', max_length=50, verbose_name='数据键名'),
        ),
        migrations.AlterField(
            model_name='ebplantsensorbinding',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eb_bindings', to='sensors.sensor', verbose_name='主模型传感器'),
        ),
        migrations.AddConstraint(
            model_name='ebplantsensorbinding',
            constraint=models.UniqueConstraint(fields=('sensor', 'data_key'), name='uniq_eb_sensor_data_key'),
        ),
    ]
