# Generated by Django 6.0.3 on 2026-06-17 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin_eb_plant', '0002_alter_ebplantdevicebinding_device_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EBPlantSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='如 反应工段 / 精馏工段', max_length=50, verbose_name='工段名')),
                ('sort_order', models.IntegerField(db_index=True, default=0, verbose_name='显示顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'EB 大屏工段',
                'verbose_name_plural': 'EB 大屏工段',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='ebplantdevicebinding',
            name='section',
            field=models.ForeignKey(blank=True, help_text='留空表示未分组（大屏归到末尾「未分组」段）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_bindings', to='plugin_eb_plant.ebplantsection', verbose_name='所属工段'),
        ),
        migrations.AddField(
            model_name='ebplantsensorbinding',
            name='section',
            field=models.ForeignKey(blank=True, help_text='留空表示未分组（大屏归到末尾「未分组」段）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor_bindings', to='plugin_eb_plant.ebplantsection', verbose_name='所属工段'),
        ),
    ]
