"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 生产环境必须通过环境变量 SECRET_KEY 传入，开发环境使用固定值
_env_secret = os.environ.get("SECRET_KEY", "")
if _env_secret:
    SECRET_KEY = _env_secret
else:
    # 仅在 DEBUG=True 时允许使用开发默认值
    _dev_debug = os.environ.get("DEBUG", "True").lower() in ("true", "1", "yes")
    if _dev_debug:
        SECRET_KEY = "django-insecure-dev-only-key-do-not-use-in-production"
    else:
        raise ImproperlyConfigured(
            "生产环境必须设置 SECRET_KEY 环境变量！"
            "请运行: python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'"
        )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True").lower() in ("true", "1", "yes")

# 允许的主机，逗号分隔，如: localhost,127.0.0.1,yourdomain.com
_allowed = os.environ.get("ALLOWED_HOSTS", "*")
ALLOWED_HOSTS = [h.strip() for h in _allowed.split(",")] if _allowed else ["*"]


# Application definition

INSTALLED_APPS = [
    # daphne 必须放在 staticfiles 之前，否则 runserver 不会接管 ASGI（Channels 文档明确要求）
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # 第三方应用
    "channels",
    "corsheaders",
    "django_extensions",  # Django Extensions
    "rest_framework",
    "rest_framework_simplejwt",  # JWT 认证
    # 本地应用
    "devices",
    "sensors",
    "automation",
    "projects",
    "resource_folders",
    "platform_settings",
    "services.realtime.apps.RealtimeConfig",
]

# 自动发现 plugins/ 子目录下的插件 app
# 注：所有发现到的插件都会加入 INSTALLED_APPS，保证 makemigrations 正常工作
# 是否真正暴露 API 由 urls.py 按 Plugin.enabled 过滤
try:
    from plugins import discover_plugins as _discover_plugins
    INSTALLED_APPS.extend(p.app_label for p in _discover_plugins())
except Exception as _e:  # pragma: no cover - 启动期间不应阻断
    import sys as _sys
    print(f"[plugins] 发现失败，已跳过: {_e}", file=_sys.stderr)

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # CORS中间件，需要放在前面
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"

# Channels channel layer：跨 worker 广播必须用 Redis（InMemoryChannelLayer
# 在 paho 后台线程 → consumer 异步线程跨线程场景下不稳定，开发期也强制 Redis）。
_REDIS_URL = os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/0")
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [_REDIS_URL],
            "capacity": 1500,
            "expiry": 30,
        },
    }
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# 通过环境变量切换：未设置 DB_USE_MYSQL 或为空时使用 SQLite

if os.environ.get("DB_USE_MYSQL", "").lower() in ("true", "1", "yes"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": os.environ.get("DB_NAME", "iot_platform"),
            "USER": os.environ.get("DB_USER", "root"),
            "PASSWORD": os.environ.get("DB_PASSWORD", ""),
            "HOST": os.environ.get("DB_HOST", "localhost"),
            "PORT": os.environ.get("DB_PORT", "3306"),
            "OPTIONS": {
                "charset": "utf8mb4",
                "init_command": "SET sql_mode='STRICT_TRANS_TABLES', default_storage_engine=INNODB",
            },
        }
    }
else:
    _sqlite_path = os.environ.get("SQLITE_DB_PATH")
    _db_name = _sqlite_path if _sqlite_path else str(BASE_DIR / "db.sqlite3")
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": _db_name,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "zh-hans"  # 中文简体

TIME_ZONE = "Asia/Shanghai"  # 中国时区

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
# Whitenoise 在 Gunicorn 下提供 Admin 等静态文件

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# CORS配置 - 允许前端访问
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Vue.js开发服务器
    "http://localhost:3000",
    "http://localhost:48080",  # Docker 前端默认端口
    "http://localhost:48081",  # Docker Admin 直连默认端口
    "http://127.0.0.1:5173",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:48080",
    "http://127.0.0.1:48081",
]

# 支持通过环境变量追加额外的 CORS 源（逗号分隔）
_extra_cors = os.environ.get("EXTRA_CORS_ORIGINS", "")
if _extra_cors:
    CORS_ALLOWED_ORIGINS.extend(o.strip() for o in _extra_cors.split(",") if o.strip())

CORS_ALLOW_CREDENTIALS = True

# 生产环境安全配置
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"
    SESSION_COOKIE_SECURE = os.environ.get("SESSION_COOKIE_SECURE", "False").lower() in ("true", "1")
    CSRF_COOKIE_SECURE = os.environ.get("CSRF_COOKIE_SECURE", "False").lower() in ("true", "1")

# CSRF 可信来源（与 CORS 配合，用于跨域 POST 等请求）
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:3000",
    "http://localhost:48080",
    "http://localhost:48081",  # Docker Admin 直连默认端口
    "http://127.0.0.1:5173",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:48080",
    "http://127.0.0.1:48081",
    # 开发时若从局域网设备访问，请添加如 "http://192.168.x.x:5173"
]

# MQTT 与设备配置：仅从 platform_settings 数据库读取
# 使用 SimpleLazyObject 延迟读取，避免 settings 加载时 DB 未就绪
# 启动前由 sensors.apps 自动执行 `configure --init --no-reload` 把 defaults.py 中的默认值写入 DB
from django.utils.functional import SimpleLazyObject
from config.platform_config import get_config

def _lazy_config(key, default, value_type=str):
    return SimpleLazyObject(lambda: get_config(key, default, value_type))

MQTT_BROKER = _lazy_config("mqtt_broker", "127.0.0.1")
MQTT_PORT = _lazy_config("mqtt_port", 1883, int)
MQTT_KEEPALIVE = _lazy_config("mqtt_keepalive", 60, int)
MQTT_USERNAME = _lazy_config("mqtt_username", "")
MQTT_PASSWORD = _lazy_config("mqtt_password", "")

# MQTT主题配置
MQTT_TOPICS = {
    "SENSOR_DATA": "iot/sensors/+/data",  # 传感器数据上报主题
    "SENSOR_STATUS": "iot/sensors/+/status",  # 传感器状态上报主题
    "SENSOR_CONTROL": "iot/sensors/+/control",  # 传感器控制主题
    "DEVICE_CONTROL": "iot/devices/+/control",  # 设备控制主题
    "DEVICE_STATUS": "iot/devices/+/status",  # 设备状态反馈主题
}

# 设备离线检测配置（秒）
DEVICE_OFFLINE_TIMEOUT = _lazy_config("device_offline_timeout", 300, int)
DEVICE_RECONNECT_ATTEMPTS = _lazy_config("device_reconnect_attempts", 3, int)
DEVICE_RECONNECT_INTERVAL = _lazy_config("device_reconnect_interval", 10, int)

# 默认主键字段类型
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django REST Framework 配置
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '5000/hour',
    },
}

# SimpleJWT 配置
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=2),      # Access Token 有效期 2 小时
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),       # Refresh Token 有效期 7 天
    'ROTATE_REFRESH_TOKENS': True,                     # 刷新时轮换 Refresh Token
    'BLACKLIST_AFTER_ROTATION': False,                  # 轮换后不加入黑名单（无需blacklist app）
    'AUTH_HEADER_TYPES': ('Bearer',),                   # Authorization: Bearer <token>
}

# 自动化规则脚本允许导入的模块白名单
# 仅允许导入可信模块，危险模块（os, subprocess, socket, sys 等）禁止引入
# 格式：逗号分隔的模块名列表
AUTOMATION_ALLOWED_IMPORTS = os.environ.get(
    "AUTOMATION_ALLOWED_IMPORTS",
    "time,datetime,math,random,json,re"
).split(",")

# 日志配置（定义于 config/logging_config.py）
from config.logging_config import LOGGING
