"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 支持从环境变量读取，Docker 部署时通过 .env 传入
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-*$z*rtci)tdzme*dmgp5v(sm^-iscz3i-1p)b5z&p3^bf4vab&")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True").lower() in ("true", "1", "yes")

# 允许的主机，逗号分隔，如: localhost,127.0.0.1,yourdomain.com
_allowed = os.environ.get("ALLOWED_HOSTS", "*")
ALLOWED_HOSTS = [h.strip() for h in _allowed.split(",")] if _allowed else ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # 第三方应用
    "corsheaders",
    "django_extensions",  # Django Extensions
    "rest_framework",
    "rest_framework_simplejwt",  # JWT 认证
    # 本地应用
    "devices",
    "sensors",
    "automation",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # CORS中间件，需要放在前面
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# 通过环境变量切换：未设置 DB_USE_MYSQL 或为空时使用 SQLite

if os.environ.get("DB_USE_MYSQL", "").lower() in ("true", "1", "yes"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": os.environ.get("DB_NAME", "iot_platform"),
            "USER": os.environ.get("DB_USER", "root"),
            "PASSWORD": os.environ.get("DB_PASSWORD", ""),
            "HOST": os.environ.get("DB_HOST", "localhost"),
            "PORT": os.environ.get("DB_PORT", "3306"),
            "OPTIONS": {
                "charset": "utf8mb4",
                "init_command": "SET sql_mode='STRICT_TRANS_TABLES', default_storage_engine=INNODB",
            },
        }
    }
else:
    _sqlite_path = os.environ.get("SQLITE_DB_PATH")
    _db_name = _sqlite_path if _sqlite_path else str(BASE_DIR / "db.sqlite3")
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": _db_name,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "zh-hans"  # 中文简体

TIME_ZONE = "Asia/Shanghai"  # 中国时区

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# CORS配置 - 允许前端访问
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Vue.js开发服务器
    "http://localhost:3000",
    "http://localhost:8080",  # Docker 前端
    "http://127.0.0.1:5173",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:8080",
]

CORS_ALLOW_CREDENTIALS = True

# CSRF 可信来源（与 CORS 配合，用于跨域 POST 等请求）
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:3000",
    "http://localhost:8080",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:8080",
    # 开发时若从局域网设备访问，请添加如 "http://192.168.x.x:5173"
]

# MQTT配置（支持环境变量，Docker 部署时便于修改）
# 若 EMQX 在本机运行，Docker 中应使用 host.docker.internal（Windows/Mac）
# 生产环境请务必通过 .env 设置 MQTT_BROKER、MQTT_PASSWORD
MQTT_BROKER = os.environ.get("MQTT_BROKER", "127.0.0.1")  # 本地开发默认，部署时请设置
MQTT_PORT = int(os.environ.get("MQTT_PORT", "1883"))
MQTT_KEEPALIVE = int(os.environ.get("MQTT_KEEPALIVE", "60"))
MQTT_USERNAME = os.environ.get("MQTT_USERNAME", "")
MQTT_PASSWORD = os.environ.get("MQTT_PASSWORD", "")

# MQTT主题配置
MQTT_TOPICS = {
    "SENSOR_DATA": "iot/sensors/+/data",  # 传感器数据上报主题
    "DEVICE_CONTROL": "iot/devices/+/control",  # 设备控制主题
    "DEVICE_STATUS": "iot/devices/+/status",  # 设备状态反馈主题
}

# 设备离线检测配置（秒）
DEVICE_OFFLINE_TIMEOUT = 300  # 5分钟无响应视为离线
DEVICE_RECONNECT_ATTEMPTS = 3  # 重连尝试次数
DEVICE_RECONNECT_INTERVAL = 10  # 重连间隔（秒）

# 默认主键字段类型
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django REST Framework 配置
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
}

# SimpleJWT 配置
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=2),      # Access Token 有效期 2 小时
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),       # Refresh Token 有效期 7 天
    'ROTATE_REFRESH_TOKENS': True,                     # 刷新时轮换 Refresh Token
    'BLACKLIST_AFTER_ROTATION': False,                  # 轮换后不加入黑名单（无需blacklist app）
    'AUTH_HEADER_TYPES': ('Bearer',),                   # Authorization: Bearer <token>
}

# 日志配置（定义于 config/logging_config.py）
from config.logging_config import LOGGING
