# Generated by Django 6.0.3 on 2026-06-19 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0012_remove_device_plant_fields'),
        ('sensors', '0006_remove_sensor_plant_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='唯一短码，如 EB / HOME，用于实时通道与对外引用', max_length=30, unique=True, verbose_name='项目代号')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('scene_type', models.CharField(choices=[('industrial', '工业装置'), ('smart_home', '智能家居'), ('custom', '自定义')], default='custom', help_text='决定展示默认风格（工业蓝白 / 暖米色等）', max_length=20, verbose_name='场景类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(db_index=True, default=0, verbose_name='显示顺序')),
                ('view_settings', models.JSONField(blank=True, default=dict, help_text='如 {"grid_cols": 4, "refresh_ms": 1000}', verbose_name='视图全局设置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '项目/场景',
                'verbose_name_plural': '项目/场景',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='如 反应工段 / 客厅', max_length=50, verbose_name='分区名')),
                ('sort_order', models.IntegerField(db_index=True, default=0, verbose_name='显示顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '项目分区',
                'verbose_name_plural': '项目分区',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='视图名')),
                ('view_type', models.CharField(choices=[('card', '卡片大屏'), ('diagram', '流程图'), ('timeseries', '时序趋势')], default='card', max_length=20, verbose_name='视图类型')),
                ('config', models.JSONField(blank=True, default=dict, help_text='类型特定：diagram 存 canvas；timeseries 存选中源+字段+默认时段；card 存网格设置', verbose_name='视图配置')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认视图')),
                ('sort_order', models.IntegerField(db_index=True, default=0, verbose_name='显示顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '项目视图',
                'verbose_name_plural': '项目视图',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDeviceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, help_text='如 P-101', max_length=50, verbose_name='位号')),
                ('area', models.CharField(blank=True, max_length=50, verbose_name='区域')),
                ('sort_order', models.IntegerField(db_index=True, default=0, verbose_name='显示顺序')),
                ('is_visible', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_members', to='devices.device', verbose_name='主模型设备')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_members', to='projects.project', verbose_name='所属项目')),
                ('section', models.ForeignKey(blank=True, help_text='留空表示未分组', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_members', to='projects.projectsection', verbose_name='所属分区')),
            ],
            options={
                'verbose_name': '项目设备成员',
                'verbose_name_plural': '项目设备成员',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('project', 'device'), name='uniq_project_device')],
            },
        ),
        migrations.CreateModel(
            name='ProjectSensorMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, help_text='如 TT-101', max_length=50, verbose_name='位号')),
                ('area', models.CharField(blank=True, help_text='如 R1 / FEED', max_length=50, verbose_name='区域')),
                ('data_key', models.CharField(blank=True, help_text='从 SensorData.data 取值的字段名，留空表示自动取唯一字段（仅在传感器只有一个字段时有意义）', max_length=50, verbose_name='数据键名')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='单位')),
                ('normal_value', models.FloatField(blank=True, null=True, verbose_name='正常值')),
                ('hi_threshold', models.FloatField(blank=True, null=True, verbose_name='高阈值')),
                ('lo_threshold', models.FloatField(blank=True, null=True, verbose_name='低阈值')),
                ('severity', models.CharField(choices=[('low', 'low'), ('mid', 'mid'), ('high', 'high'), ('critical', 'critical')], default='mid', max_length=20, verbose_name='严重度')),
                ('sort_order', models.IntegerField(db_index=True, default=0, verbose_name='显示顺序')),
                ('is_visible', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_members', to='projects.project', verbose_name='所属项目')),
                ('section', models.ForeignKey(blank=True, help_text='留空表示未分组（展示时归到末尾「未分组」段）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor_members', to='projects.projectsection', verbose_name='所属分区')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_members', to='sensors.sensor', verbose_name='主模型传感器')),
            ],
            options={
                'verbose_name': '项目传感器成员',
                'verbose_name_plural': '项目传感器成员',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('project', 'sensor', 'data_key'), name='uniq_project_sensor_data_key')],
            },
        ),
    ]
