# Generated by Django 6.0.3 on 2026-06-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_section_scoped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectview',
            name='view_type',
            field=models.CharField(choices=[('card', '卡片大屏'), ('diagram', '流程图'), ('timeseries', '时序趋势'), ('control', '自动化控制')], default='card', max_length=20, verbose_name='视图类型'),
        ),
    ]
