# Generated by Django 6.0.3 on 2026-05-15 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_code', models.CharField(db_index=True, help_text='与 Sensor.plant_code 对应，例如 "EB"', max_length=50, verbose_name='装置代号')),
                ('name', models.CharField(max_length=100, verbose_name='画板名称')),
                ('description', models.TextField(blank=True, verbose_name='画板描述')),
                ('canvas', models.JSONField(default=dict, help_text='包含 version / viewport / nodes / edges', verbose_name='画布数据')),
                ('is_default', models.BooleanField(default=False, help_text='同一 plant_code 仅可有一张 default；运行态默认打开 default', verbose_name='是否默认画板')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plant_diagrams', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': 'P&ID 画板',
                'verbose_name_plural': 'P&ID 画板',
                'ordering': ['plant_code', 'sort_order', '-updated_at'],
                'indexes': [models.Index(fields=['plant_code', 'is_default'], name='plugin_plan_plant_c_19823f_idx')],
            },
        ),
    ]
