# Generated by Django 6.0.1 on 2026-02-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AutomationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="规则名称")),
                ("description", models.TextField(blank=True, verbose_name="规则描述")),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "automation_script",
                    models.TextField(
                        help_text="\n        Python 脚本，实现完整的触发判断和执行逻辑\n        \n        可用变量（通过 devices 字典访问）：\n        - devices: 字典，包含所有关联的设备和传感器\n          访问方式：devices['device_id']\n        - 每个设备对象包含：\n          - current_state: 当前状态字典\n          - variables_schema: 变量定义\n          - 控制方法：set_variable_value(key, value)\n        \n        返回值：\n        - True: 执行成功\n        - False: 执行失败或不满足触发条件\n        \n        示例1 - 温度控制风扇：\n        ```python\n        # 获取传感器和设备\n        sensor = devices.get('DHT11-001')\n        fan = devices.get('FAN-001')\n        \n        # 判断触发条件\n        if sensor and sensor.current_state.get('temperature', 0) > 30:\n            # 执行动作\n            if fan:\n                fan.set_variable_value('power_state', True)\n                fan.set_variable_value('speed', 3)\n            return True\n        return False\n        ```\n        \n        示例2 - 复杂逻辑：\n        ```python\n        # 获取多个传感器\n        temp_sensor = devices.get('DHT11-001')\n        pressure_sensor = devices.get('BMP180-001')\n        \n        # 复杂判断逻辑\n        temp = temp_sensor.current_state.get('temperature', 0) if temp_sensor else 0\n        pressure = pressure_sensor.current_state.get('pressure', 0) if pressure_sensor else 0\n        \n        # 温度高于35或气压低于950时触发\n        if temp > 35 or pressure < 950:\n            # 控制多个设备\n            led = devices.get('LED-001')\n            buzzer = devices.get('BUZZER-001')\n            \n            if led:\n                led.set_variable_value('power_state', True)\n            if buzzer:\n                buzzer.set_variable_value('active', True)\n            \n            return True\n        return False\n        ```\n        ",
                        verbose_name="自动化脚本",
                    ),
                ),
                (
                    "device_list",
                    models.JSONField(
                        default=list,
                        help_text='\n        脚本中可访问的设备和传感器列表\n        格式：[\n            {\n                "device_id": "DHT11-001",\n                "device_type": "Sensor",\n                "name": "客厅温湿度传感器",\n                "description": "用于读取温湿度数据"\n            },\n            {\n                "device_id": "FAN-001", \n                "device_type": "Device",\n                "name": "客厅风扇",\n                "description": "根据温度自动控制"\n            }\n        ]\n        ',
                        verbose_name="设备与传感器列表",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "自动化规则",
                "verbose_name_plural": "自动化规则",
                "ordering": ["-created_at"],
            },
        ),
    ]
