# Generated by Django 5.2.8 on 2026-02-15 12:18

import django.db.models.deletion
from django.db import migrations, models


def create_humidity_overflow_print_script(apps, schema_editor):
    AutomationScript = apps.get_model("automation", "AutomationScript")
    AutomationScript.objects.get_or_create(
        script_id="humidity_overflow_print",
        defaults={
            "name": "湿度超 80% 打印",
            "description": "读取 DHT11-WEMOS-001 最近一条数据，湿度>80%时在终端打印",
            "module_path": "automation.script.humidity_overflow_print",
            "function_name": "run",
            "is_enabled": True,
        },
    )


def remove_humidity_overflow_print_script(apps, schema_editor):
    AutomationScript = apps.get_model("automation", "AutomationScript")
    AutomationScript.objects.filter(script_id="humidity_overflow_print").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0002_alter_automationrule_automation_script_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationScript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "script_id",
                    models.CharField(
                        help_text="唯一标识，如 humidity_overflow_print，engine 通过此 ID 调用",
                        max_length=80,
                        unique=True,
                        verbose_name="脚本ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="脚本名称")),
                ("description", models.TextField(blank=True, verbose_name="说明")),
                (
                    "module_path",
                    models.CharField(
                        help_text="如 automation.script.humidity_overflow_print",
                        max_length=200,
                        verbose_name="模块路径",
                    ),
                ),
                (
                    "function_name",
                    models.CharField(
                        default="run", max_length=50, verbose_name="函数名"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "自动化脚本",
                "verbose_name_plural": "自动化脚本",
                "ordering": ["script_id"],
            },
        ),
        migrations.AddField(
            model_name="automationrule",
            name="script",
            field=models.ForeignKey(
                blank=True,
                help_text="若设置则执行此预定义脚本，否则使用下方内联脚本",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rules",
                to="automation.automationscript",
                verbose_name="关联脚本",
            ),
        ),
        migrations.RunPython(create_humidity_overflow_print_script, remove_humidity_overflow_print_script),
    ]
