# Generated by Django 5.2.8 on 2026-02-16 00:12

from django.db import migrations, models


def copy_automation_script_to_script(apps, schema_editor):
    """将 automation_script 内容迁移到 script"""
    AutomationRule = apps.get_model("automation", "AutomationRule")
    for rule in AutomationRule.objects.all():
        if hasattr(rule, 'automation_script') and rule.automation_script:
            rule.script = rule.automation_script
            rule.save(update_fields=['script'])
    # 使用 raw SQL 因为 migration 状态下 automation_script 可能已被移除
    # 此函数在 AddField script 之后、RemoveField automation_script 之前执行


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0004_merge_script_into_rule"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationrule",
            name="script",
            field=models.TextField(
                blank=True,
                default="",
                help_text="\n        Python 脚本，实现触发判断和执行逻辑。\n\n        可用变量：devices 字典，key 为 device_id，value 为包装对象。\n\n        【传感器 Sensor】\n        - current_state: 最新 SensorData.data（来自 sensor.data_records）\n        - 数据字段由 SensorType.data_fields 定义，如 temperature、humidity\n\n        【设备 Device】\n        - current_state: 最新 DeviceData.data（来自 device.data_records）\n        - send_command(name, params): 发送控制命令，命令名来自 DeviceType.commands\n        - 如 high/low（电平）、turn_on/turn_off（开关）等，取决于设备类型\n\n        返回值：True 执行成功，False 不满足条件或执行失败\n\n        示例 - 温度过高时开启 LED（设备类型需定义 high 命令）：\n        ```python\n        sensor = devices.get('DHT11-WEMOS-001')  # device_id 与 Sensor 表一致\n        led = devices.get('SG_80_01')            # device_id 与 Device 表一致\n\n        if sensor and sensor.current_state:\n            temp = sensor.current_state.get('temperature', 0)\n            if temp > 30 and led:\n                led.send_command('high', {})  # 发送 high 命令\n                return True\n        return False\n        ```\n        ",
                verbose_name="脚本",
            ),
        ),
        migrations.RunPython(copy_automation_script_to_script, noop),
        migrations.RemoveField(
            model_name="automationrule",
            name="automation_script",
        ),
        migrations.RemoveField(
            model_name="automationrule",
            name="function_name",
        ),
        migrations.RemoveField(
            model_name="automationrule",
            name="module_path",
        ),
        migrations.RemoveField(
            model_name="automationrule",
            name="script_id",
        ),
        migrations.AlterField(
            model_name="automationrule",
            name="device_list",
            field=models.JSONField(
                default=list,
                help_text='\n        脚本中可访问的设备和传感器，device_id 需与 devices.Device 或 sensors.Sensor 表中的 device_id 对应。\n        格式示例：\n        [\n            {"device_id": "DHT11-WEMOS-001", "device_type": "Sensor", "name": "温湿度传感器"},\n            {"device_id": "SG_80_01", "device_type": "Device", "name": "LED灯"}\n        ]\n        ',
                verbose_name="设备与传感器列表",
            ),
        ),
    ]
