# Generated by Django 5.2.8 on 2026-02-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0005_simplify_to_script_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationrule",
            name="script_id",
            field=models.CharField(
                blank=True,
                help_text="唯一标识，通过 execute_by_script_id('xxx') 调用执行，如 humidity_overflow_print、humidity_alert",
                max_length=50,
                unique=True,
                verbose_name="脚本唯一ID",
            ),
        ),
        migrations.AlterField(
            model_name="automationrule",
            name="script",
            field=models.TextField(
                blank=True,
                help_text="\n        Python 脚本，Arduino 风格：from engine import sensors, devices，定义带 loop() 的控制器类。\n\n        engine 由引擎注入，含 sensors、devices。控制器类 __init__ 相当于 setup()，loop() 返回 True/False。\n\n        参见 automation/script/sample_file.txt 完整示例。\n        ",
                verbose_name="脚本",
            ),
        ),
    ]
