# Generated by Django 5.2.8 on 2026-02-17 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0006_add_script_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="automationrule",
            name="is_enabled",
        ),
    ]
