# Generated by Django 5.2.8 on 2026-02-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0007_remove_is_enabled_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationrule",
            name="error_message",
            field=models.TextField(
                blank=True,
                help_text="当 process_status 为 error_stopped 时的错误详情",
                verbose_name="错误信息",
            ),
        ),
        migrations.AddField(
            model_name="automationrule",
            name="is_launched",
            field=models.BooleanField(
                default=False,
                help_text="标记该规则是否应持续轮询执行",
                verbose_name="是否启动轮询",
            ),
        ),
        migrations.AddField(
            model_name="automationrule",
            name="process_status",
            field=models.CharField(
                choices=[
                    ("idle", "未启动"),
                    ("running", "正在运行"),
                    ("stopped_by_user", "由用户停止"),
                    ("error_stopped", "由错误停止"),
                ],
                default="idle",
                max_length=20,
                verbose_name="进程状态",
            ),
        ),
    ]
