# Generated by Django 5.2.8 on 2026-02-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0008_add_polling_state_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationrule",
            name="poll_interval",
            field=models.PositiveIntegerField(
                default=30,
                help_text="轮询执行的时间间隔，单位为秒，最小 1 秒",
                verbose_name="轮询间隔（秒）",
            ),
        ),
    ]
