# Generated by Django 5.2.8 on 2026-02-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0009_add_poll_interval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automationrule",
            name="script_id",
            field=models.CharField(
                help_text="唯一标识，通过 execute_by_script_id('xxx') 调用执行，如 humidity_overflow_print、humidity_alert",
                max_length=50,
                unique=True,
                verbose_name="脚本唯一ID",
            ),
        ),
    ]
